"""PharmaLens exercise taxonomy.

Packs organize current and future exercises. `planned` packs are discovery metadata
only; they are not executable until an ExerciseManifest + engine handler exists.
"""
EXERCISE_PACKS = [
 {"id":"market_commercial","name":"Market & Commercial Intelligence","description":"Market, company, molecule, product and portfolio intelligence.","personas":["brand_manager","commercial_manager","analyst"],"current":["product-01","product-02","product-03","product-04","product-05","product-09","product-15"],"planned":["market_definition","market_size_value_volume","market_growth_mat_ytd","competitive_landscape","brand_performance_decomposition","new_entry_tracking","price_pack_architecture","opportunity_scoring"]},
 {"id":"forecast_planning","name":"Forecasting & Planning","description":"Forecast, scenario, demand and target planning.","personas":["demand_planner","brand_manager","finance"],"current":["product-06","product-08","product-10"],"planned":["forecast_accuracy","forecast_bias","rolling_forecast","new_product_forecast","patient_based_forecast","target_setting_top_down","target_setting_bottom_up","territory_target_allocation"]},
 {"id":"sales_sfe","name":"Sales & SFE","description":"Sales force effectiveness, achievement and field execution.","personas":["sales_manager","field_force","commercial_excellence"],"current":["product-13","product-14"],"planned":["achievement_analysis","territory_performance","rep_performance","call_plan","hcp_segmentation","hcp_targeting","coverage_frequency","activity_effectiveness","incentive_simulation"]},
 {"id":"commercial_finance","name":"Commercial Finance","description":"Budget, variance, ROI and commercial financial planning.","personas":["finance","commercial_manager"],"current":["product-17"],"planned":["budget_vs_actual","price_volume_mix","roci","promotion_roi","launch_roi","reforecast","fx_sensitivity","gross_to_net","incentive_budget"]},
 {"id":"market_access_heor","name":"Market Access & HEOR","description":"Access, value, outcomes and payer decision support.","personas":["market_access","heor","medical_affairs"],"current":[],"planned":["payer_landscape","access_barrier_mapping","value_proposition","budget_impact","cost_effectiveness","mcda","treatment_pathway","patient_flow","reimbursement_scenario","formulary_strategy"]},
 {"id":"medical_affairs","name":"Medical Affairs","description":"Scientific engagement and evidence planning.","personas":["medical_affairs","msl","medical_manager"],"current":[],"planned":["kol_mapping","kol_segmentation","scientific_engagement_plan","medical_activity_plan","evidence_gap","publication_plan","congress_plan","medical_insight_clustering","scientific_response_trends"]},
 {"id":"supply_procurement","name":"Supply Chain & Procurement","description":"Supply, inventory, hospital demand and procurement intelligence.","personas":["supply_chain","procurement","hospital_manager"],"current":["product-11","product-12"],"planned":["stock_cover","stockout_risk","expiry_risk","reorder_point","safety_stock","supplier_performance","hospital_consumption","allocation_by_region","procurement_plan","logistics_risk"]},
 {"id":"tender","name":"Tender & Institutional Business","description":"Tender opportunity, institutional demand and award intelligence.","personas":["tender_manager","key_account","hospital_manager"],"current":[],"planned":["tender_pipeline","tender_opportunity_score","hospital_quantity_plan","competitor_award_tracking","bid_no_bid","tender_price_scenario","institutional_share","award_probability_inputs","tender_post_mortem"]},
 {"id":"quality","name":"Quality Intelligence","description":"Quality event, complaint, CAPA and risk intelligence.","personas":["quality","qa_manager","operations"],"current":[],"planned":["complaint_trend","deviation_trend","capa_effectiveness","root_cause_patterns","supplier_quality","batch_risk","quality_kpi_scorecard","audit_finding_trend"]},
 {"id":"retail_category","name":"Retail & Category Management","description":"Pharmacy chain, retail category and assortment intelligence.","personas":["category_manager","key_account","retail_manager"],"current":[],"planned":["category_growth","assortment_productivity","sku_rationalization","chain_performance","distribution_gap","promotion_effectiveness","basket_affinity","price_ladder","store_cluster"]},
 {"id":"launch_gtm","name":"Launch & Go-To-Market","description":"Launch readiness, GTM, channel and execution planning.","personas":["launch_team","brand_manager","business_development"],"current":["product-07","product-16"],"planned":["launch_readiness","launch_sequence","channel_strategy","distribution_strategy","launch_kpi_tree","early_launch_tracking","competitor_response_scenario"]},
]
PACK_BY_ID={p["id"]:p for p in EXERCISE_PACKS}
def list_exercise_packs():
    return EXERCISE_PACKS
