from enum import Enum

class ExerciseType(str, Enum):
    DESCRIPTIVE = "DESCRIPTIVE"
    DIAGNOSTIC = "DIAGNOSTIC"
    PREDICTIVE = "PREDICTIVE"
    DECISION_SUPPORT = "DECISION_SUPPORT"
    OPTIMIZATION = "OPTIMIZATION"
    MONITORING = "MONITORING"
    REVIEW = "REVIEW"
    PLANNING = "PLANNING"
    OPPORTUNITY = "OPPORTUNITY"
    SCENARIO = "SCENARIO"
    COMPOSITE = "COMPOSITE"

class ExerciseStatus(str, Enum):
    CREATED = "CREATED"
    VALIDATING = "VALIDATING"
    DATA_CHECK = "DATA_CHECK"
    RUNNING = "RUNNING"
    QUALITY_CHECK = "QUALITY_CHECK"
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"

class DataAvailabilityStatus(str, Enum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    INSUFFICIENT = "INSUFFICIENT"

class QualityStatus(str, Enum):
    PASS = "PASS"
    WARNING = "WARNING"
    BLOCK = "BLOCK"
    UNKNOWN = "UNKNOWN"
