from .sales import SALES_EXERCISE_DEFINITIONS
from .marketing import MARKETING_EXERCISE_DEFINITIONS
from .sfe import SFE_EXERCISE_DEFINITIONS
from .target import TARGET_EXERCISE_DEFINITIONS
from .hcp_kol import HCP_KOL_EXERCISE_DEFINITIONS
from .business_development import BUSINESS_DEVELOPMENT_EXERCISE_DEFINITIONS
from .market_access import MARKET_ACCESS_EXERCISE_DEFINITIONS
from .launch import LAUNCH_EXERCISE_DEFINITIONS
from .portfolio import PORTFOLIO_EXERCISE_DEFINITIONS
from .finance import FINANCE_EXERCISE_DEFINITIONS

from .trade import TRADE_EXERCISE_DEFINITIONS
from .events import EVENT_EXERCISE_DEFINITIONS
from .medical import MEDICAL_EXERCISE_DEFINITIONS
from .executive import EXECUTIVE_EXERCISE_DEFINITIONS
from .strategic import STRATEGIC_EXERCISE_DEFINITIONS

CANONICAL_EXERCISE_DEFINITIONS = sum((
    SALES_EXERCISE_DEFINITIONS, MARKETING_EXERCISE_DEFINITIONS, SFE_EXERCISE_DEFINITIONS,
    TARGET_EXERCISE_DEFINITIONS, HCP_KOL_EXERCISE_DEFINITIONS, BUSINESS_DEVELOPMENT_EXERCISE_DEFINITIONS,
    MARKET_ACCESS_EXERCISE_DEFINITIONS, LAUNCH_EXERCISE_DEFINITIONS, PORTFOLIO_EXERCISE_DEFINITIONS,
    FINANCE_EXERCISE_DEFINITIONS, TRADE_EXERCISE_DEFINITIONS, EVENT_EXERCISE_DEFINITIONS,
    MEDICAL_EXERCISE_DEFINITIONS, EXECUTIVE_EXERCISE_DEFINITIONS, STRATEGIC_EXERCISE_DEFINITIONS,
), ())

__all__ = [
    "SALES_EXERCISE_DEFINITIONS", "MARKETING_EXERCISE_DEFINITIONS", "SFE_EXERCISE_DEFINITIONS",
    "TARGET_EXERCISE_DEFINITIONS", "HCP_KOL_EXERCISE_DEFINITIONS", "BUSINESS_DEVELOPMENT_EXERCISE_DEFINITIONS",
    "MARKET_ACCESS_EXERCISE_DEFINITIONS", "LAUNCH_EXERCISE_DEFINITIONS", "PORTFOLIO_EXERCISE_DEFINITIONS",
    "FINANCE_EXERCISE_DEFINITIONS", "TRADE_EXERCISE_DEFINITIONS", "EVENT_EXERCISE_DEFINITIONS",
    "MEDICAL_EXERCISE_DEFINITIONS", "EXECUTIVE_EXERCISE_DEFINITIONS", "STRATEGIC_EXERCISE_DEFINITIONS",
    "CANONICAL_EXERCISE_DEFINITIONS",
]
